/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulariosInventarios;

import baseDatos.baseDatos;
import formularios.frm_editarInstrumento;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Keng
 */
public class frm_listaInvetario extends javax.swing.JFrame {
    private baseDatos bd;
    private Connection conn = null;
    private ButtonGroup checkBoxGroup;
    private DefaultTableModel tblModel;
    /**
     * Creates new form frm_listaInvetario
     */
    public frm_listaInvetario() {
        initComponents();
        
        //checkbox
        checkBoxGroup = new ButtonGroup();
        checkBoxGroup.add(cb_si);
        checkBoxGroup.add(cb_no);
        
        //desactivar botones
        btn_editar.setEnabled(false);
        btn_eliminar.setEnabled(false);
        
        //obtener datos desde la bd
        try {
            conn = bd.abrirBD();
            Statement stmt = conn.createStatement();
            String query = "SELECT inv.id as id, ins.nombre as instrumento, ins.valor as valor, inv.cantidad_disponible as cantidad_disponible, inv.disponible as disponible"
                    + " FROM inventarios inv inner join instrumentos ins on ins.id = inv.id_instrumento "
                    + " where ins.disponible = '0' "
                    + " and inv.eliminado = '0'";
            ResultSet rs = stmt.executeQuery(query);
            
            while(rs.next()){
              String id = rs.getString("id");
              String instrumento = rs.getString("instrumento");
              String valor = rs.getString("valor");
              String cantidad = rs.getString("cantidad_disponible");
              String disponible = rs.getString("disponible");
              
              if(disponible.equals("0")){
                  disponible = "Si";
              }else{
                  disponible = "No";
              }
              
              String tbData [] = {id, instrumento, valor, cantidad, disponible};
              tblModel = (DefaultTableModel)table_listaInventario.getModel();
              
              tblModel.addRow(tbData);
            }
            
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        cb_si = new javax.swing.JRadioButton();
        cb_no = new javax.swing.JRadioButton();
        txt_buscar = new javax.swing.JTextField();
        btn_atras = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_cargarLista = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_listaInventario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Lista de Inventarios");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Disponibilidad"));

        cb_si.setText("Si");
        cb_si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_siActionPerformed(evt);
            }
        });

        cb_no.setText("No");
        cb_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_noActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(cb_si)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_no)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_si)
                    .addComponent(cb_no))
                .addContainerGap())
        );

        btn_atras.setText("Atras");
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_cargarLista.setText("Refrescar Lista");
        btn_cargarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarListaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nota: Para editar y eliminar primero debe seleccionar el registro");

        table_listaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Instrumento", "Valor", "Cantidad Disponible", "Disponible"
            }
        ));
        table_listaInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_listaInventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_listaInventario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_atras, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cargarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_atras, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_cargarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_siActionPerformed
        txt_buscar.setText("");
        
        tblModel = (DefaultTableModel)table_listaInventario.getModel();
        tblModel.setRowCount(0);
        
        //obtener datos desde la bd
        try {
            Statement stmt = conn.createStatement();
            String query = "SELECT inv.id as id, ins.nombre as instrumento, ins.valor as valor, inv.cantidad_disponible as cantidad_disponible, inv.disponible as disponible"
                    + " FROM inventarios inv inner join instrumentos ins on ins.id = inv.id_instrumento "
                    + " where ins.disponible = '0' "
                    + " and inv.disponible = '0' "
                    + " and inv.eliminado = '0'";
            ResultSet rs = stmt.executeQuery(query);
            
            while(rs.next()){
              String id = rs.getString("id");
              String instrumento = rs.getString("instrumento");
              String valor = rs.getString("valor");
              String cantidad = rs.getString("cantidad_disponible");
              String disponible = rs.getString("disponible");
              
              if(disponible.equals("0")){
                  disponible = "Si";
              }else{
                  disponible = "No";
              }
              
              String tbData [] = {id, instrumento, valor, cantidad, disponible};
              tblModel = (DefaultTableModel)table_listaInventario.getModel();
              
              tblModel.addRow(tbData);
            }
            
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_cb_siActionPerformed

    private void cb_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_noActionPerformed
      txt_buscar.setText("");
        
        tblModel = (DefaultTableModel)table_listaInventario.getModel();
        tblModel.setRowCount(0);
        
        //obtener datos desde la bd
        try {
            Statement stmt = conn.createStatement();
            String query = "SELECT inv.id as id, ins.nombre as instrumento, ins.valor as valor, inv.cantidad_disponible as cantidad_disponible, inv.disponible as disponible"
                    + " FROM inventarios inv inner join instrumentos ins on ins.id = inv.id_instrumento "
                    + " where ins.disponible = '0' "
                    + " and inv.disponible = '1' "
                    + " and inv.eliminado = '0'";
            ResultSet rs = stmt.executeQuery(query);
            
            while(rs.next()){
              String id = rs.getString("id");
              String instrumento = rs.getString("instrumento");
              String valor = rs.getString("valor");
              String cantidad = rs.getString("cantidad_disponible");
              String disponible = rs.getString("disponible");
              
              if(disponible.equals("0")){
                  disponible = "Si";
              }else{
                  disponible = "No";
              }
              
              String tbData [] = {id, instrumento, valor, cantidad, disponible};
              tblModel = (DefaultTableModel)table_listaInventario.getModel();
              
              tblModel.addRow(tbData);
            }
            
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_cb_noActionPerformed

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        this.dispose();
        System.err.println("Base de datos cerrada!");
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        if(txt_buscar.getText().equals("") == false){
            //limpiar tabla
            tblModel = (DefaultTableModel)table_listaInventario.getModel();
            tblModel.setRowCount(0);
        
            String buscar = txt_buscar.getText();
            //obtener datos desde la bd
            try {
                conn = bd.abrirBD();
                Statement stmt = conn.createStatement();
                String query = "SELECT inv.id as id, ins.nombre as instrumento, ins.valor as valor, inv.cantidad_disponible as cantidad_disponible, inv.disponible as disponible"
                    + " FROM inventarios inv inner join instrumentos ins on ins.id = inv.id_instrumento "
                    + " WHERE inv.eliminado = '0'"
                    + " AND ins.valor like '%" + buscar + "%' "
                    + " OR ins.nombre like '%" + buscar +"%' ";
              
                ResultSet rs = stmt.executeQuery(query);

                while(rs.next()){
                    String id = rs.getString("id");
                    String instrumento = rs.getString("instrumento");
                    String valor = rs.getString("valor");
                    String cantidad = rs.getString("cantidad_disponible");
                    String disponible = rs.getString("disponible");

                    if(disponible.equals("0")){
                        disponible = "Si";
                    }else{
                        disponible = "No";
                    }

                  String tbData [] = {id, instrumento, valor, cantidad, disponible};
                  tblModel = (DefaultTableModel)table_listaInventario.getModel();

                  tblModel.addRow(tbData);
                }

            }
            catch(SQLException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        //limpiar search
        txt_buscar.setText("");
        
        //limpiar radio buttons
        checkBoxGroup.clearSelection();
        
        tblModel = (DefaultTableModel)table_listaInventario.getModel();
        int selectedRowIndex = table_listaInventario.getSelectedRow();
        
        String id = tblModel.getValueAt(selectedRowIndex, 0).toString(); 
        
            String query = "UPDATE inventarios SET eliminado = '1' WHERE id = ?";
            try{
                PreparedStatement pstmt = conn.prepareStatement(query);
                pstmt.setString(1, id);
                int row = pstmt.executeUpdate();
                
                if(row == 1){
                    JOptionPane.showMessageDialog(null, "Se ha eliminado instrumento");
                    JOptionPane.showMessageDialog(null, "Por favor refresque la lista");
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar instrumento");
                }
            }
            catch (SQLException e){
                e.printStackTrace();
                System.err.println(e.getMessage());
            }

        btn_editar.setEnabled(false);
        btn_eliminar.setEnabled(false); 
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        tblModel = (DefaultTableModel)table_listaInventario.getModel();
        int selectedRowIndex = table_listaInventario.getSelectedRow();
        
        String id = tblModel.getValueAt(selectedRowIndex, 0).toString();
        String cantidad = tblModel.getValueAt(selectedRowIndex, 3).toString();
        String disponibilidad = tblModel.getValueAt(selectedRowIndex, 4).toString();
         
        frm_editarInventario editar = new frm_editarInventario(id, cantidad, disponibilidad);
        editar.setVisible(true);
        
        btn_editar.setEnabled(false);
        btn_eliminar.setEnabled(false);
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_cargarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarListaActionPerformed
        //limpiar search
        txt_buscar.setText("");
        
        //limpiar radio buttons
        checkBoxGroup.clearSelection();
        
        //limpiar tabla
        tblModel = (DefaultTableModel)table_listaInventario.getModel();
        tblModel.setRowCount(0);
        
        try {
            conn = bd.abrirBD();
            Statement stmt = conn.createStatement();
            String query = "SELECT inv.id as id, ins.nombre as instrumento, ins.valor as valor, inv.cantidad_disponible as cantidad_disponible, inv.disponible as disponible"
                    + " FROM inventarios inv inner join instrumentos ins on ins.id = inv.id_instrumento "
                    + " where ins.disponible = '0' "
                    + " and inv.eliminado = '0'";
            ResultSet rs = stmt.executeQuery(query);
            
            while(rs.next()){
              String id = rs.getString("id");
              String instrumento = rs.getString("instrumento");
              String valor = rs.getString("valor");
              String cantidad = rs.getString("cantidad_disponible");
              String disponible = rs.getString("disponible");
              
              if(disponible.equals("0")){
                  disponible = "Si";
              }else{
                  disponible = "No";
              }
              
              String tbData [] = {id, instrumento, valor, cantidad, disponible};
              tblModel = (DefaultTableModel)table_listaInventario.getModel();
              
              tblModel.addRow(tbData);
            }
            
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_cargarListaActionPerformed

    private void table_listaInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_listaInventarioMouseClicked
        // TODO add your handling code here:
         btn_editar.setEnabled(true);
        btn_eliminar.setEnabled(true);
    }//GEN-LAST:event_table_listaInventarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_listaInvetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_listaInvetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_listaInvetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_listaInvetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_listaInvetario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cargarLista;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JRadioButton cb_no;
    private javax.swing.JRadioButton cb_si;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_listaInventario;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
