/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulariosClasesMusicales;

import baseDatos.baseDatos;
import java.sql.*;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Keng
 */
public class frm_listaClases extends javax.swing.JFrame {
    private baseDatos bd;
    private Connection conn = null;
    private ButtonGroup checkBoxGroup;
    private DefaultTableModel tblModel;
    /**
     * Creates new form frm_listaClases
     */
    public frm_listaClases() {
        initComponents();
        
        //desactivar botones
        btn_editar.setEnabled(false);
        btn_eliminar.setEnabled(false);
        
        //obtener datos desde la bd
        try {
            conn = bd.abrirBD();
            Statement stmt = conn.createStatement();
            String query = "SELECT * FROM clases where eliminado = '0'";
            ResultSet rs = stmt.executeQuery(query);
            
            while(rs.next()){
                String id = rs.getString("id");
                String dia = rs.getString("dia_clase");
                String valor = rs.getString("costo");
                String instrumento = rs.getString("instrumento");

                String fechaCreacion = rs.getString("fecha_de_creacion");
              
                String tbData [] = {id, dia, valor, instrumento, fechaCreacion};
                tblModel = (DefaultTableModel)table_listaClases.getModel();
              
                tblModel.addRow(tbData);
            }
            
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_atras1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_cargarLista = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_listaClases = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Lista de Clases Musicales");

        txt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarActionPerformed(evt);
            }
        });

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_atras1.setText("Atras");
        btn_atras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atras1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nota: Para editar y eliminar primero debe seleccionar el registro");

        btn_cargarLista.setText("Refrescar Lista");
        btn_cargarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarListaActionPerformed(evt);
            }
        });

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        table_listaClases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Dia", "Valor", "Instrumento", "Fecha de Creacion"
            }
        ));
        table_listaClases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_listaClasesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_listaClases);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btn_atras1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(143, 143, 143)
                        .addComponent(btn_cargarLista, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(btn_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_atras1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btn_cargarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        if(txt_buscar.getText().equals("") == false){
            //limpiar tabla
            tblModel = (DefaultTableModel)table_listaClases.getModel();
            tblModel.setRowCount(0);

            String buscar = txt_buscar.getText();
            //obtener datos desde la bd
            try {
                conn = bd.abrirBD();
                Statement stmt = conn.createStatement();
                String query = "SELECT *"
                + "FROM clases "
                + "WHERE eliminado = '0' "
                + "AND dia_clase like '%" + buscar +"%' "
                + "OR costo like '%" + buscar + "%' "
                + "OR instrumento like '%" + buscar + "%' "
                 + "OR id like '%" + buscar + "%' "
                + "OR fecha_de_creacion like '%" + buscar + "%' ";
                ResultSet rs = stmt.executeQuery(query);

                while(rs.next()){
                     String id = rs.getString("id");
                    String dia = rs.getString("dia_clase");
                    String valor = rs.getString("costo");
                    String instrumento = rs.getString("instrumento");

                    String fechaCreacion = rs.getString("fecha_de_creacion");

                    String tbData [] = {id, dia, valor, instrumento, fechaCreacion};
                    tblModel = (DefaultTableModel)table_listaClases.getModel();

                    tblModel.addRow(tbData);
                }

            }
            catch(SQLException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_atras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atras1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.err.println("Base de datos cerrada!");
    }//GEN-LAST:event_btn_atras1ActionPerformed

    private void btn_cargarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarListaActionPerformed
        //limpiar search
        txt_buscar.setText("");
        
        //limpiar tabla
        tblModel = (DefaultTableModel)table_listaClases.getModel();
        tblModel.setRowCount(0);
        
         try {
            conn = bd.abrirBD();
            Statement stmt = conn.createStatement();
            String query = "SELECT * FROM clases WHERE eliminado = '0'";
            ResultSet rs = stmt.executeQuery(query);
            
            while(rs.next()){
                String id = rs.getString("id");
                String dia = rs.getString("dia_clase");
                String valor = rs.getString("costo");
                String instrumento = rs.getString("instrumento");

                String fechaCreacion = rs.getString("fecha_de_creacion");

                String tbData [] = {id, dia, valor, instrumento, fechaCreacion};
                tblModel = (DefaultTableModel)table_listaClases.getModel();
              
              tblModel.addRow(tbData);
            }
            
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_cargarListaActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        tblModel = (DefaultTableModel)table_listaClases.getModel();
        int selectedRowIndex = table_listaClases.getSelectedRow();
        
        String id = tblModel.getValueAt(selectedRowIndex, 0).toString();
        String dia = tblModel.getValueAt(selectedRowIndex, 1).toString();
        String valor = tblModel.getValueAt(selectedRowIndex, 2).toString();
        String instrumento = tblModel.getValueAt(selectedRowIndex, 3).toString();
        
        frm_editarClase editar = new frm_editarClase(id, dia, valor, instrumento);
        editar.setVisible(true);
        
        btn_editar.setEnabled(false);
        btn_eliminar.setEnabled(false);
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
       //limpiar search
        txt_buscar.setText("");
        
        tblModel = (DefaultTableModel)table_listaClases.getModel();
        int selectedRowIndex = table_listaClases.getSelectedRow();
        
        String id = tblModel.getValueAt(selectedRowIndex, 0).toString(); 
        
        String query = "UPDATE clases SET eliminado = '1' WHERE id = ?";
        try{
                PreparedStatement pstmt = conn.prepareStatement(query);
                pstmt.setString(1, id);
                int row = pstmt.executeUpdate();
                
                if(row == 1){
                    JOptionPane.showMessageDialog(null, "Se ha eliminado instrumento");
                    JOptionPane.showMessageDialog(null, "Por favor refresque la lista");
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar instrumento");
                }
        }
        catch (SQLException e){
            e.printStackTrace();
            System.err.println(e.getMessage());
        }

        btn_editar.setEnabled(false);
        btn_eliminar.setEnabled(false);
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void table_listaClasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_listaClasesMouseClicked
        // TODO add your handling code here:
         btn_editar.setEnabled(true);
        btn_eliminar.setEnabled(true);
    }//GEN-LAST:event_table_listaClasesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_listaClases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_listaClases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_listaClases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_listaClases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_listaClases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atras1;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cargarLista;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_listaClases;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
